name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install project dependencies
        run: cd vscode-workspaces-gnome && pnpm install

      - name: Build project
        run: cd vscode-workspaces-gnome && make && make pack

      - name: Upload release
        uses: softprops/action-gh-release@v2.0.6
        with:
          files: ./vscode-workspaces-gnome/vscode-workspaces-gnome.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
